apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
    replicas: 2
    strategy:
        type: RollingUpdate
    selector:
        matchLabels:
          app: myapp
    template:
        metadata:
          labels:
            app: myapp
        spec:
          containers:
            - name: frontendapp
              image: anupdhude/frontendrds
              ports:
                - containerPort: 80
                  protocol: TCP
              resources:
                requests:
                      memory: "64Mi"
                      cpu: "125m"
                limits:
                      memory: "128Mi"
                      cpu: "250m"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa
spec:
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: myapp
    minReplicas: 1
    maxReplicas: 3
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 50
        
