apiVersion: apps/v1
kind: Deployment
metadata: 
  name: file.txt
  labels:
    app: core
spec:
    strategy:
      type: RollingUpdate
      rollingUpdate:
            maxSurge: 1
            maxUnavailabel: 1
    selector:
     matchLabels:
       app: core2
    replicas: 5
    template:
        metadata:
          labels:
            name: nginxapp
            app: core2
        spec:
            containers:
              - name: nginxapp
                image: httpd:latest
                ports:
                  - containerPort: 80
                    protocol: TCP 


---
apiVersion: v1
kind: Service
metadata: 
  name: nodeportservice
spec:
  type: NodePort
  selector:
    app: core
  ports:
    - port: 80
      targetPort: 80
      name: nginx
      protocol: TCP
