apiVersion: v1
kind: Pod 
metadata: 
  name: prodpod
  namespace: siddhant
  labels:   
    app: ms07
spec: 
    containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort : 80
              protocol : TCP
              name: nginx
--- 
apiVersion: v1 
kind: Service
metadata:
    name: b24service
    namespace: siddhant
spec: 
    type: NodePort
    selector: 
      app: ms07
    ports: 
        - port: 80 
          targetPort: 80
          protocol: TCP 
    
