apiVersion: apps/v1
kind:  ReplicaSet
metadata: 
  name: sid
  labels:
    app: sidapp
spec:
    selector: 
      matchExpressions:      
         -  { key: app, operator: In , values: [sidapp,  new-app]}
    replicas: 2
    template:
      metadata:
        labels:
          name: nginxapp
          app: sidapp
      spec:
        containers:
          - name: nginxapp
            image: nginx:latest 
            ports:
                - containerPort: 80
                  protocol: TCP
