apiVersion: apps/v1
kind:  StatefulSet
metadata: 
  name: statefull
  labels:
    app: myapp
spec:
    selector: 
      matchLabels: 
          app: myapp
    replicas: 4
    template:
      metadata:
        labels:
          name: mdb
          app: myapp
      spec:
        containers:
          - name: mysql
            image: mysql
            ports:
                - containerPort: 3306
                  protocol: TCP
            env:
                 - name: MYSQL_ROOT_PASSWORD
                   value: "1234"      
